name: prune-juice

version: '0.5'
maintainer: Dan Fithian <daniel.m.fithian@gmail.com>
license: MIT
copyright: 2020 Dan Fithian
category: Development
synopsis: 'Prune unused Haskell dependencies'
description: 'Prune unused Haskell dependencies - see README at <https://github.com/dfithian/prune-juice#readme>'
github: dfithian/prune-juice

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-redundant-constraints
  - -Wincomplete-uni-patterns
  - -eventlog

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

dependencies:
  - aeson
  - base < 5.0
  - bytestring
  - Cabal
  - cabal-install-parsers
  - containers
  - directory
  - filepath
  - hpack
  - megaparsec
  - mtl
  - process
  - text
  - yaml

extra-source-files:
  - stack.yaml
  - package.yaml

library:
  source-dirs:
    - src

tests:
  test:
    main: main.hs
    source-dirs:
      - test
    dependencies:
      - file-path-th
      - hspec

      - prune-juice

executables:
  prune-juice:
    main: main.hs
    source-dirs:
      - app
    dependencies:
      - optparse-applicative

      - prune-juice
